"""car info

Revision ID: 720663f69091
Revises: 9623371a82eb
Create Date: 2021-06-24 00:15:50.110401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720663f69091'
down_revision = '9623371a82eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mpg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('upgrades', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
